$global:Services = @(
    "pip-services-logging-node"
    "pip-services-logging-python"
    "pip-services-eventlog-node"
    "pip-services-registry-node"
    "pip-services-settings-node"
    "pip-services-counters-node"
    "pip-services-statistics-node"
    "pip-services-blobs-node"
    "pip-services-facets-node"
    "pip-services-search-node"
    "pip-services-email-node"
    "pip-services-sms-node"
    "pip-facade-infrastructure-node"
)

$global:Clients = @(
    "pip-clients-logging-node"
    "pip-clients-logging-python"
    "pip-clients-eventlog-node"
    "pip-clients-registry-node"
    "pip-clients-settings-node"
    "pip-clients-counters-node"
    "pip-clients-statistics-node"
    "pip-clients-blobs-node"
    "pip-clients-tempblobs-node"
    "pip-clients-facets-node"
    "pip-clients-search-node"
    "pip-clients-email-node"
    "pip-clients-sms-node"
)
